### ISSUE TITLE
Node check errorloop

### ISSUE THREAD

**Issue by jd-rk9** [pycom/Pymakr#19] opened 2019-03-12 11:16 UTC
I noticed a minor issue while installing on Windows, I didn't had node.js installed. This gives an errorloop, easy to solve by installing node but the loop it self made vscode unworkable.

**Comment by RalphHogenbirk** [comment] 2019-03-12 11:19
HI @sicarii-13 thanks for reporting this. Pymakr has some code that should check your node.js installation and give a nice popup warning about it, but it sounds like that feature is not working properly in your case. I'll give it a quick test later today, see if there is a bug.

**Comment by jd-rk9** [comment] 2019-03-12 11:25
Hi thx for the quick reply, @RalphHogenbirk If you need more information from me let me know. btw the hardware packaging is a big+

**Comment by RalphHogenbirk** [comment] 2019-03-12 14:36
@sicarii-13 i've checked the code and the warning that tells you there is no nodejs installed works. The problem is that it then just continues to start up and gets stuck in the loop. I've just pushed a fix on the develop branch (https://github.com/pycom/pymakr-vsc/commit/4e1a3da02dcfc9dc22a1138802ffd337245814d3)

ps. we're in the wrong repo :) This is the old pymakr desktop app, you were looking for this repo: https://github.com/pycom/pymakr-vsc/. But no need to re-post the issue there, it's been fixed!

**Closed as completed** 2019-03-14 12:22 UTC
